layerrules = true
kill_bind = "ctrl+shift+alt, h"
version = 1

[windows]
scale = 1.5
items_per_row = 9

[windows.overview]
strip_html_from_workspace_title = true
modifier = "Super"
key = "Tab"
filter_by = []               
hide_filtered = true


[windows.overview.launcher]
default_terminal = "kitty"
launch_modifier = "Alt"
width = 50
max_items = 5
show_when_empty = true
animate_launch_ms = 250

[windows.overview.launcher.plugins.path]